--region Enums
CREATE TYPE PAYMENT_METHOD AS ENUM ('pay_after_receiving', 'pay_after_buying');
CREATE TYPE SEX AS ENUM ('m', 'f');
--endregion


--region Tables
--region Person
CREATE TABLE table_emails
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    email TEXT                                                 NOT NULL CHECK ( email != '' )
);

CREATE TABLE table_phone_numbers
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    phone_number TEXT                                                 NOT NULL CHECK ( phone_number != '' )
);

CREATE TABLE table_persons
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name            TEXT                                                 NOT NULL CHECK ( name != '' ),
    surname         TEXT                                                 NOT NULL CHECK ( surname != '' ),
    patronymic      TEXT                                                 NOT NULL,
    sex             SEX                                                  NOT NULL CHECK ( sex = 'm' or sex = 'f' ),
    email_id        INTEGER                                              NOT NULL,
    phone_number_id INTEGER                                              NOT NULL,
    FOREIGN KEY (email_id) REFERENCES table_emails (id),
    FOREIGN KEY (phone_number_id) REFERENCES table_phone_numbers (id)
);

CREATE TABLE table_clients
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    person_id         INTEGER                                              NOT NULL,
    discount          NUMERIC(4, 2)                                        NOT NULL,
    agreed_on_mailing BOOLEAN                                              NOT NULL DEFAULT false,
    FOREIGN KEY (person_id) REFERENCES table_persons (id)
);

CREATE TABLE table_employees
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    person_id        INTEGER                                              NOT NULL,
    position         TEXT                                                 NOT NULL CHECK ( position != '' ),
    hire_date        DATE                                                 NOT NULL,
    salary_in_rubles NUMERIC(7, 2)                                        NOT NULL CHECK ( salary_in_rubles > 0 ),
    FOREIGN KEY (person_id) REFERENCES table_persons (id)
);

--endregion


--region Tables of product
CREATE TABLE table_manufacturers
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name                TEXT                                                 NOT NULL CHECK ( name != '' ),
    address             TEXT                                                 NOT NULL CHECK ( address != '' ),
    phone_number        TEXT                                                 NOT NULL CHECK ( phone_number != '' ),
    website             TEXT                                                 NOT NULL,
    manufacture_country TEXT                                                 NOT NULL CHECK ( manufacture_country != '' ),
    brand               TEXT                                                 NOT NULL CHECK ( brand != '' ),
    license             TEXT                                                 NOT NULL CHECK ( license != '' )
);

CREATE TABLE table_units
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    unit_type TEXT                                                 NOT NULL CHECK ( unit_type != '' )
);

CREATE TABLE table_product_types
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name TEXT                                                 NOT NULL CHECK ( name != '' )
);

CREATE TABLE table_products
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    type_id         INTEGER                                              NOT NULL,
    unit_id         INTEGER                                              NOT NULL,
    manufacturer_id INTEGER                                              NOT NULL,
    name            TEXT                                                 NOT NULL CHECK ( name != '' ),
    description     TEXT                                                 NOT NULL CHECK ( description != '' ),
    series          TEXT                                                 NOT NULL CHECK ( series != '' ),
    purchase_price  NUMERIC(7, 2)                                        NOT NULL CHECK ( purchase_price > 0),
    unit_value      NUMERIC(10, 2)                                       NOT NULL CHECK ( unit_value > 0 ),
    production_date DATE                                                 NOT NULL,
    expiration_date DATE                                                 NOT NULL CHECK ( expiration_date > production_date ),
    selling_price   NUMERIC(7, 2)                                        NOT NULL CHECK ( purchase_price > purchase_price ),
    FOREIGN KEY (type_id) REFERENCES table_product_types (id),
    FOREIGN KEY (unit_id) REFERENCES table_units (id),
    FOREIGN KEY (manufacturer_id) REFERENCES table_manufacturers (id)
);

CREATE TABLE table_product_price_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    id_product INTEGER NOT NULL,
    selling_price NUMERIC(7, 2) NOT NULL CHECK ( selling_price > 0 ),
    date DATE NOT NULL
);
--endregion


--region Tables of purchase
CREATE TABLE table_salespoint
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    address TEXT                                                 NOT NULL CHECK ( address != '' ),
    name    TEXT                                                 NOT NULL CHECK ( name != '' )
);

CREATE TABLE table_online_purchases
(
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    id_delivery_salespoint INTEGER                                              NOT NULL,
    product_code           INTEGER                                              NOT NULL,
    payment                PAYMENT_METHOD                                       NOT NULL,
    FOREIGN KEY (id_delivery_salespoint) REFERENCES table_salespoint (id)
);

CREATE TABLE table_offline_purchases
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    client_id     INTEGER                                              NOT NULL DEFAULT 0,
    employee_id   INTEGER                                              NOT NULL,
    salespoint_id INTEGER,
    FOREIGN KEY (client_id) REFERENCES table_clients (id),
    FOREIGN KEY (employee_id) REFERENCES table_employees (id),
    FOREIGN KEY (salespoint_id) REFERENCES table_salespoint (id)
);

CREATE TABLE table_purchases
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    online_purchase_id  INTEGER CHECK ( online_purchase_id = 1 or online_purchase_id = 0 ) DEFAULT 0,
    offline_purchase_id INTEGER CHECK ( online_purchase_id = 1 or online_purchase_id = 0 ) DEFAULT 0,
    product_id          INTEGER                                              NOT NULL,
    purchase_date       DATE                                                 NOT NULL,
    FOREIGN KEY (online_purchase_id) REFERENCES table_online_purchases (id),
    FOREIGN KEY (offline_purchase_id) REFERENCES table_offline_purchases (id),
    FOREIGN KEY (product_id) REFERENCES table_products (id)
);
--endregion
--endregion