--region Enums
CREATE TYPE PAYMENT_METHOD AS ENUM ('pay_after_receiving', 'pay_after_buying');
CREATE TYPE SEX AS ENUM ('m', 'f');
--endregion


--region Tables
--region Person
CREATE TABLE table_persons
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL CHECK ( name != '' ),
    surname    TEXT NOT NULL CHECK ( surname != '' ),
    patronymic TEXT NOT NULL,
    sex        SEX  NOT NULL CHECK ( sex = 'm' or sex = 'f' )
);

CREATE TABLE table_emails
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INTEGER,
    email     TEXT NOT NULL CHECK ( email != '' ),
    FOREIGN KEY (person_id) REFERENCES table_persons (id)
);

CREATE TABLE table_phone_numbers
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id    INTEGER,
    phone_number TEXT NOT NULL CHECK ( phone_number != '' ),
    FOREIGN KEY (person_id) REFERENCES table_persons (id)
);

CREATE TABLE table_clients
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id         INTEGER       NOT NULL,
    discount          NUMERIC(4, 2),
    agreed_on_mailing BOOLEAN       NOT NULL DEFAULT false,
    FOREIGN KEY (person_id) REFERENCES table_persons (id)
);

CREATE TABLE table_position
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position         TEXT NOT NULL CHECK ( position != '' ),
    salary_in_rubles NUMERIC(7, 2)
);

CREATE TABLE table_employees
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id   INTEGER NOT NULL,
    position_id INTEGER,
    hire_date   DATE    NOT NULL,
    is_working  BOOLEAN NOT NULL DEFAULT false,
    FOREIGN KEY (person_id) REFERENCES table_persons (id),
    FOREIGN KEY (position_id) REFERENCES table_position (id)
);
--endregion


--region Tables of product
CREATE TABLE table_manufacturers
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name                TEXT                                                 NOT NULL CHECK ( name != '' ),
    address             TEXT                                                 NOT NULL CHECK ( address != '' ),
    phone_number        TEXT                                                 NOT NULL CHECK ( phone_number != '' ),
    website             TEXT                                                 NOT NULL,
    manufacture_country TEXT                                                 NOT NULL CHECK ( manufacture_country != '' ),
    brand               TEXT                                                 NOT NULL CHECK ( brand != '' ),
    license             TEXT                                                 NOT NULL CHECK ( license != '' )
);

CREATE TABLE table_units
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    unit_type TEXT                                                 NOT NULL CHECK ( unit_type != '' )
);

CREATE TABLE table_product_types
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name TEXT                                                 NOT NULL CHECK ( name != '' )
);

CREATE TABLE table_products
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    type_id         INTEGER                                              NOT NULL,
    unit_id         INTEGER                                              NOT NULL,
    manufacturer_id INTEGER                                              NOT NULL,
    name            TEXT                                                 NOT NULL CHECK ( name != '' ),
    description     TEXT                                                 NOT NULL CHECK ( description != '' ),
    series          TEXT                                                 NOT NULL CHECK ( series != '' ),
    purchase_price  NUMERIC(7, 2)                                        NOT NULL CHECK ( purchase_price > 0),
    unit_value      NUMERIC(10, 2)                                       NOT NULL CHECK ( unit_value > 0 ),
    production_date DATE                                                 NOT NULL,
    expiration_date DATE                                                 NOT NULL CHECK ( expiration_date > production_date ),
    selling_price   NUMERIC(7, 2)                                        NOT NULL CHECK ( purchase_price > purchase_price ),
    FOREIGN KEY (type_id) REFERENCES table_product_types (id),
    FOREIGN KEY (unit_id) REFERENCES table_units (id),
    FOREIGN KEY (manufacturer_id) REFERENCES table_manufacturers (id)
);

CREATE TABLE table_product_price_histories
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    id_product    INTEGER                                              NOT NULL,
    selling_price NUMERIC(7, 2)                                        NOT NULL CHECK ( selling_price > 0 ),
    date          DATE                                                 NOT NULL
);
--endregion


--region Tables of purchase
CREATE TABLE table_salespoints
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    address TEXT                                                 NOT NULL CHECK ( address != '' ),
    name    TEXT                                                 NOT NULL CHECK ( name != '' )
);

CREATE TABLE table_online_purchases
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    salespoint_id INTEGER                                              NOT NULL,
    product_id    INTEGER                                              NOT NULL,
    product_code  INTEGER                                              NOT NULL,
    payment       PAYMENT_METHOD                                       NOT NULL,
    FOREIGN KEY (salespoint_id) REFERENCES table_salespoints (id),
    FOREIGN KEY (product_id) REFERENCES table_products (id)
);

CREATE TABLE table_offline_purchases
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    product_id    INTEGER                                              NOT NULL,
    client_id     INTEGER                                              NOT NULL DEFAULT 0,
    employee_id   INTEGER                                              NOT NULL,
    salespoint_id INTEGER,
    FOREIGN KEY (client_id) REFERENCES table_clients (id),
    FOREIGN KEY (employee_id) REFERENCES table_employees (id),
    FOREIGN KEY (salespoint_id) REFERENCES table_salespoints (id),
    FOREIGN KEY (product_id) REFERENCES table_products (id)
);

CREATE TABLE table_purchases
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    online_purchase_id  INTEGER DEFAULT 0,
    offline_purchase_id INTEGER DEFAULT 0,
    purchase_date       DATE                                                 NOT NULL,
    FOREIGN KEY (online_purchase_id) REFERENCES table_online_purchases (id),
    FOREIGN KEY (offline_purchase_id) REFERENCES table_offline_purchases (id)
);
--endregion
--endregion


--region Data
INSERT INTO table_persons(name, surname, patronymic, sex)
VALUES ('Emily', 'Johnson', 'Marie', 'f'),
       ('Michael', 'Anderson', '', 'm'),
       ('Olivia', 'Thompson', 'Grace', 'f'),
       ('Daniel', 'Roberts', 'Alexander', 'm'),
       ('Sophia', 'Miller', '', 'f'),
       ('William', 'Harris', 'Edward', 'm'),
       ('Ava', 'Clark', 'Louise', 'f'),
       ('James', 'Walker', '', 'm'),
       ('Isabella', 'Lewis', 'Jane', 'f'),
       ('Benjamin', 'Hall', 'Charles', 'm');

INSERT INTO table_emails(person_id, email)
VALUES (1, 'emily.johnson@example.com'),
       (1, 'emily.johnson.work@example.com'),
       (3, 'olivia.thompson@example.com'),
       (4, 'daniel.roberts@example.com'),
       (6, 'william.harris@example.com'),
       (6, 'william.harris.work@example.com'),
       (8, 'james.walker@example.com'),
       (9, 'isabella.lewis@example.com'),
       (9, 'isabella.lewis.promo@example.com'),
       (10, 'benjamin.hall@example.com');

INSERT INTO table_phone_numbers(person_id, phone_number)
VALUES (2, '+7 901 234-56-78'),
       (2, '+7 901 234-56-79'),
       (3, '+7 912 345-67-80'),
       (5, '+7 913 456-78-81'),
       (5, '+7 913 456-78-82'),
       (7, '+7 914 567-89-83'),
       (8, '+7 915 678-90-84'),
       (10, '+7 916 789-01-85'),
       (10, '+7 916 789-01-86'),
       (1, '+7 917 890-12-87');
--endregion