CREATE TYPE SEX AS ENUM ('m', 'f');


CREATE TABLE table_persons
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL CHECK ( name != '' ),
    surname    TEXT NOT NULL CHECK ( surname != '' ),
    patronymic TEXT NOT NULL,
    sex        SEX  NOT NULL
);

CREATE TABLE table_emails
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id            INTEGER REFERENCES table_persons (id),
    email                TEXT    NOT NULL CHECK ( email LIKE '%@%'),
    is_agreed_on_mailing BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE table_phone_numbers
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id    INTEGER REFERENCES table_persons (id),
    phone_number TEXT NOT NULL CHECK ( phone_number != '' )
);

CREATE TABLE table_discounts
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  TEXT                                                 NOT NULL CHECK ( name != '' ),
    value NUMERIC(4, 2)
);

CREATE TABLE table_clients
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id   INTEGER NOT NULL REFERENCES table_persons (id),
    discount_id INTEGER DEFAULT NULL REFERENCES table_discounts (id)
);

CREATE TABLE table_position
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position         TEXT NOT NULL CHECK ( position != '' ),
    salary_in_rubles NUMERIC(7, 2)
);

CREATE TABLE table_employees
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id   INTEGER NOT NULL REFERENCES table_persons (id),
    position_id INTEGER NOT NULL REFERENCES table_position (id),
    hire_date   DATE    NOT NULL,
    is_working  BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE table_employee_change_histories
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supervisor_id   INTEGER REFERENCES table_employees (id),
    employee_id     INTEGER REFERENCES table_employees (id),
    old_position_id INTEGER REFERENCES table_position (id),
    new_position_id INTEGER REFERENCES table_position (id),
    change_date     DATE NOT NULL,
    change_reason   TEXT NOT NULL CHECK ( change_reason != '')
);