CREATE TYPE SEX AS ENUM ('m', 'f');


CREATE TABLE table_persons
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL CHECK ( name != '' ),
    surname    TEXT NOT NULL CHECK ( surname != '' ),
    patronymic TEXT NOT NULL,
    sex        SEX  NOT NULL
);

CREATE TABLE table_emails
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id            INTEGER,
    email                TEXT    NOT NULL CHECK ( email != '' ),
    is_agreed_on_mailing BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (person_id) REFERENCES table_persons (id)
);

CREATE TABLE table_phone_numbers
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id    INTEGER,
    phone_number TEXT NOT NULL CHECK ( phone_number != '' ),
    FOREIGN KEY (person_id) REFERENCES table_persons (id)
);

CREATE TABLE table_clients
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INTEGER NOT NULL,
    discount  NUMERIC(4, 2),
    FOREIGN KEY (person_id) REFERENCES table_persons (id)
);

CREATE TABLE table_position
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position         TEXT NOT NULL CHECK ( position != '' ),
    salary_in_rubles NUMERIC(7, 2)
);

CREATE TABLE table_employees
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id   INTEGER NOT NULL,
    position_id INTEGER NOT NULL,
    hire_date   DATE    NOT NULL,
    is_working  BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (person_id) REFERENCES table_persons (id),
    FOREIGN KEY (position_id) REFERENCES table_position (id)
);

CREATE TABLE table_employee_change_histories (
                                                 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 supervisor_id INTEGER,
                                                 employee_id INTEGER,
                                                 old_position_id INTEGER,
                                                 new_position_id INTEGER,
                                                 change_date DATE NOT NULL,
                                                 change_reason TEXT NOT NULL CHECK ( change_reason != ''),
                                                 FOREIGN KEY (employee_id) REFERENCES table_employees(id),
                                                 FOREIGN KEY (supervisor_id) REFERENCES table_employees(id),
                                                 FOREIGN KEY (old_position_id) REFERENCES table_position(id),
                                                 FOREIGN KEY (new_position_id) REFERENCES table_position(id)
);