CREATE TABLE table_manufacturers
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name                TEXT                                                 NOT NULL CHECK ( name != '' ),
    address             TEXT                                                 NOT NULL CHECK ( address != '' ),
    phone_number        TEXT                                                 NOT NULL CHECK ( phone_number != '' ),
    website             TEXT                                                 NOT NULL,
    manufacture_country TEXT                                                 NOT NULL CHECK ( manufacture_country != '' ),
    brand               TEXT                                                 NOT NULL CHECK ( brand != '' ),
    license             TEXT                                                 NOT NULL CHECK ( license != '' )
);

CREATE TABLE table_units
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    unit_type TEXT                                                 NOT NULL CHECK ( unit_type != '' )
);

CREATE TABLE table_product_types
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name TEXT                                                 NOT NULL CHECK ( name != '' )
);

CREATE TABLE table_products
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    type_id         INTEGER                                              NOT NULL,
    unit_id         INTEGER                                              NOT NULL,
    manufacturer_id INTEGER                                              NOT NULL,
    name            TEXT                                                 NOT NULL CHECK ( name != '' ),
    description     TEXT                                                 NOT NULL CHECK ( description != '' ),
    series          TEXT                                                 NOT NULL CHECK ( series != '' ),
    purchase_price  NUMERIC(7, 2)                                        NOT NULL CHECK ( purchase_price > 0),
    unit_value      NUMERIC(10, 2)                                       NOT NULL CHECK ( unit_value > 0 ),
    production_date DATE                                                 NOT NULL,
    expiration_date DATE                                                 NOT NULL CHECK ( expiration_date > production_date ),
    selling_price   NUMERIC(7, 2)                                        NOT NULL CHECK ( purchase_price > purchase_price ),
    FOREIGN KEY (type_id) REFERENCES table_product_types (id),
    FOREIGN KEY (unit_id) REFERENCES table_units (id),
    FOREIGN KEY (manufacturer_id) REFERENCES table_manufacturers (id)
);

CREATE TABLE table_product_price_histories
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    product_id    INTEGER                                              NOT NULL,
    selling_price NUMERIC(7, 2)                                        NOT NULL CHECK ( selling_price > 0 ),
    date          DATE                                                 NOT NULL
);