CREATE TYPE PAYMENT_METHOD AS ENUM ('pay_after_receiving', 'pay_after_buying');


CREATE TABLE table_salespoints
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    address TEXT                                                 NOT NULL CHECK ( address != '' ),
    name    TEXT                                                 NOT NULL CHECK ( name != '' )
);

CREATE TABLE table_online_purchases
(
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    salespoint_delivery_id INTEGER                                              NOT NULL REFERENCES table_salespoints (id),
    product_id             INTEGER                                              NOT NULL REFERENCES table_products (id),
    order_code             INTEGER                                              NOT NULL,
    payment                PAYMENT_METHOD                                       NOT NULL
);

CREATE TABLE table_offline_purchases
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    salespoint_id INTEGER REFERENCES table_salespoints (id),
    product_id    INTEGER                                              NOT NULL REFERENCES table_products (id),
    employee_id   INTEGER                                              NOT NULL REFERENCES table_employees (id),
    client_id     INTEGER DEFAULT NULL REFERENCES table_clients (id)
);

CREATE TABLE table_purchases
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    online_purchase_id  INTEGER DEFAULT NULL REFERENCES table_online_purchases (id),
    offline_purchase_id INTEGER DEFAULT NULL REFERENCES table_offline_purchases (id),
    purchase_date       DATE                                                 NOT NULL
);