CREATE TYPE PAYMENT_METHOD AS ENUM ('pay_after_receiving', 'pay_after_buying');


CREATE TABLE table_salespoints
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    address TEXT                                                 NOT NULL CHECK ( address != '' ),
    name    TEXT                                                 NOT NULL CHECK ( name != '' )
);

CREATE TABLE table_online_purchases
(
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    salespoint_delivery_id INTEGER                                              NOT NULL,
    product_id             INTEGER                                              NOT NULL,
    order_code             INTEGER                                              NOT NULL,
    payment                PAYMENT_METHOD                                       NOT NULL,
    FOREIGN KEY (salespoint_delivery_id) REFERENCES table_salespoints (id),
    FOREIGN KEY (product_id) REFERENCES table_products (id)
);

CREATE TABLE table_offline_purchases
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    product_id    INTEGER                                              NOT NULL,
    employee_id   INTEGER                                              NOT NULL,
    client_id     INTEGER DEFAULT NULL,
    salespoint_id INTEGER,
    FOREIGN KEY (client_id) REFERENCES table_clients (id),
    FOREIGN KEY (employee_id) REFERENCES table_employees (id),
    FOREIGN KEY (salespoint_id) REFERENCES table_salespoints (id),
    FOREIGN KEY (product_id) REFERENCES table_products (id)
);

CREATE TABLE table_purchases
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    online_purchase_id  INTEGER DEFAULT NULL,
    offline_purchase_id INTEGER DEFAULT NULL,
    purchase_date       DATE                                                 NOT NULL,
    FOREIGN KEY (online_purchase_id) REFERENCES table_online_purchases (id),
    FOREIGN KEY (offline_purchase_id) REFERENCES table_offline_purchases (id)
);